### ISSUE TITLE
Can you help about that?

### ISSUE THREAD

**Issue by samcheung1** [SY-Xuan/CFME#1]
i gets a error:
Traceback (most recent call last):
  File "E:/CFME-main/demo.py", line 20, in <module>
    tracker.init(frame, bbox)
  File "E:\CFME-main\mecfTracker.py", line 30, in init
    self.tracker.init([bbox[0],bbox[1],bbox[2],bbox[3]], frame)
  File "E:\CFME-main\kcftracker.py", line 274, in init
    assert(roi[2]>0 and roi[3]>0)
AssertionError

can you help me?
QAQ

**Comment by SY-Xuan** [comment]
You need to modify the bounding box of the tracking object by yourself in the demo.py.
https://github.com/SY-Xuan/CFME/blob/c8a4abfa658013d2c9dd1967c995ee799201e32e/demo.py#L13
